'use strict';

/**
 * Demo machines — the 8 PRD machines plus 8 more, each with a telemetry
 * behavior profile used ONLY by the deterministic simulator/warm-up.
 * Profiles never appear in API responses as "real" telemetry.
 */

const MACHINES = [
  {
    id: 'mach_extruder',
    name: 'Primary Extruder',
    type: 'EXTRUSION',
    status: 'RUNNING',
    image: 'images/extruder.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-ext-001',
    schedule: { startTime: '08:00', sleepTime: '17:00' },
    thresholds: { temperature_c: { max: 60 }, power_kw: { max: 12 } },
    telemetry: {
      temperature_c: { base: 52, amp: 3, noise: 0.6, phase: 1.2 },
      power_kw: { base: 9.2, amp: 1.4, noise: 0.35, phase: 0.6 },
      load_pct: { base: 68, amp: 10, noise: 2, phase: 0.6 },
    },
    episode: { metric: 'temperature_c', startMin: -150, durationMin: 150, delta: 11, kind: 'rise' },
  },
  {
    id: 'mach_mill',
    name: 'Milling Machine Alpha',
    type: 'MILLING',
    status: 'RUNNING',
    image: 'images/milling.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-mil-002',
    thresholds: { temperature_c: { max: 65 }, power_kw: { max: 15 } },
    telemetry: {
      temperature_c: { base: 46, amp: 4, noise: 0.7, phase: 2.1 },
      power_kw: { base: 7.8, amp: 2.2, noise: 0.4, phase: 3.3 },
      load_pct: { base: 55, amp: 15, noise: 2.5, phase: 3.3 },
      vibration_mm_s: { base: 1.8, amp: 0.5, noise: 0.15, phase: 1.0 },
    },
    episode: null,
  },
  {
    id: 'mach_mixer',
    name: 'Chemical Mixer',
    type: 'MIXING',
    status: 'RUNNING',
    image: 'images/mixer.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-mix-003',
    thresholds: { temperature_c: { max: 70 }, power_kw: { max: 9 } },
    telemetry: {
      temperature_c: { base: 41, amp: 5, noise: 0.8, phase: 0.9 },
      power_kw: { base: 5.4, amp: 1.1, noise: 0.3, phase: 2.4 },
    },
    episode: null,
  },
  {
    id: 'mach_press',
    name: 'Pressing Machine',
    type: 'PRESSING',
    status: 'IDLE',
    image: 'images/press.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-pre-004',
    thresholds: { temperature_c: { max: 60 }, power_kw: { max: 18 } },
    telemetry: {
      temperature_c: { base: 34, amp: 2, noise: 0.5, phase: 1.7 },
      power_kw: { base: 0.8, amp: 0.6, noise: 0.2, phase: 0.4 },
    },
    episode: null,
  },
  {
    id: 'mach_robot',
    name: 'Assembly Robot R1',
    type: 'ROBOT',
    status: 'RUNNING',
    image: 'images/robot.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-rob-005',
    thresholds: { temperature_c: { max: 55 }, power_kw: { max: 6 } },
    telemetry: {
      temperature_c: { base: 38, amp: 3, noise: 0.6, phase: 2.8 },
      power_kw: { base: 2.6, amp: 0.9, noise: 0.25, phase: 1.5 },
      load_pct: { base: 62, amp: 18, noise: 3, phase: 1.5 },
    },
    episode: null,
  },
  {
    id: 'mach_molder',
    name: 'Injection Molder 3000',
    type: 'MOLDING',
    status: 'RUNNING',
    image: 'images/molder.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-mol-006',
    thresholds: { temperature_c: { max: 75 }, power_kw: { max: 20 } },
    telemetry: {
      temperature_c: { base: 58, amp: 6, noise: 0.9, phase: 0.2 },
      power_kw: { base: 11.5, amp: 2.5, noise: 0.5, phase: 2.0 },
      load_pct: { base: 72, amp: 12, noise: 2, phase: 2.0 },
    },
    episode: null,
  },
  {
    id: 'mach_welding',
    name: 'Welding Station WS2',
    type: 'WELDING',
    status: 'OFF',
    image: 'images/welding.jpg',
    plantId: 'plant_secondary',
    externalDeviceId: 'dev-wel-007',
    thresholds: { temperature_c: { max: 65 }, power_kw: { max: 14 } },
    telemetry: {
      temperature_c: { base: 28, amp: 1, noise: 0.4, phase: 0.5 },
      power_kw: { base: 0.2, amp: 0.2, noise: 0.1, phase: 0.5 },
    },
    episode: null,
  },
  {
    id: 'mach_conveyor',
    name: 'Conveyor Belt Sys C5',
    type: 'CONVEYOR',
    status: 'RUNNING',
    image: 'images/conveyor.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-con-008',
    thresholds: { temperature_c: { max: 50 }, power_kw: { max: 7 } },
    telemetry: {
      temperature_c: { base: 36, amp: 2, noise: 0.5, phase: 3.9 },
      power_kw: { base: 3.8, amp: 1.0, noise: 0.3, phase: 5.2 },
      load_pct: { base: 58, amp: 12, noise: 2, phase: 5.2 },
    },
    episode: null,
  },
  {
    id: 'mach_lathe',
    name: 'CNC Lathe TL-2',
    type: 'MACHINING',
    status: 'RUNNING',
    image: 'images/chip_belt.jpg',
    plantId: 'plant_secondary',
    externalDeviceId: 'dev-lat-009',
    thresholds: { temperature_c: { max: 62 }, power_kw: { max: 11 } },
    telemetry: {
      temperature_c: { base: 44, amp: 4, noise: 0.7, phase: 4.1 },
      power_kw: { base: 6.2, amp: 1.8, noise: 0.35, phase: 3.9 },
      vibration_mm_s: { base: 2.1, amp: 0.6, noise: 0.18, phase: 2.2 },
    },
    episode: { metric: 'vibration_mm_s', startMin: -240, durationMin: 240, delta: 2.4, kind: 'rise' },
  },
  {
    id: 'mach_hpress',
    name: 'Hydraulic Press HP-1',
    type: 'PRESSING',
    status: 'MAINTENANCE',
    image: 'images/clamping_bolts.jpg',
    plantId: 'plant_secondary',
    externalDeviceId: 'dev-hpr-010',
    thresholds: { temperature_c: { max: 60 }, power_kw: { max: 16 } },
    telemetry: {
      temperature_c: { base: 32, amp: 2, noise: 0.5, phase: 1.1 },
      power_kw: { base: 1.0, amp: 0.5, noise: 0.2, phase: 0.8 },
    },
    episode: null,
  },
  {
    id: 'mach_cooling',
    name: 'Cooling Tower CT-3',
    type: 'UTILITY',
    status: 'RUNNING',
    image: 'images/pump_impeller.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-ct-011',
    thresholds: { temperature_c: { max: 45 }, power_kw: { max: 9 } },
    telemetry: {
      temperature_c: { base: 38, amp: 3, noise: 0.8, phase: 2.6 },
      power_kw: { base: 5.0, amp: 1.2, noise: 0.3, phase: 4.4 },
    },
    episode: { metric: 'temperature_c', startMin: -400, durationMin: 90, delta: 9, kind: 'spike' },
  },
  {
    id: 'mach_compressor',
    name: 'Air Compressor AC-2',
    type: 'UTILITY',
    status: 'RUNNING',
    image: 'images/motor_pulley.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-ac-012',
    thresholds: { temperature_c: { max: 70 }, power_kw: { max: 22 } },
    telemetry: {
      temperature_c: { base: 55, amp: 5, noise: 1.0, phase: 0.3 },
      power_kw: { base: 13.0, amp: 3.0, noise: 0.6, phase: 1.9 },
      pressure_bar: { base: 7.2, amp: 0.6, noise: 0.2, phase: 1.9 },
    },
    episode: null,
  },
  {
    id: 'mach_packaging',
    name: 'Packaging Line PL-1',
    type: 'PACKAGING',
    status: 'FAULT',
    image: 'images/feeder_roller.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-pkg-013',
    thresholds: { temperature_c: { max: 55 }, power_kw: { max: 8 } },
    telemetry: {
      temperature_c: { base: 40, amp: 3, noise: 0.6, phase: 5.5 },
      power_kw: { base: 4.5, amp: 1.0, noise: 0.3, phase: 5.5 },
    },
    episode: { metric: 'power_kw', startMin: -120, durationMin: 120, delta: 9, kind: 'rise' },
  },
  {
    id: 'mach_palletizer',
    name: 'Palletizer Robot PR-1',
    type: 'ROBOT',
    status: 'OFFLINE',
    image: 'images/gripper.jpg',
    plantId: 'plant_secondary',
    externalDeviceId: 'dev-plz-014',
    thresholds: { temperature_c: { max: 55 }, power_kw: { max: 6 } },
    telemetry: {
      temperature_c: { base: 30, amp: 1.5, noise: 0.4, phase: 3.2 },
      power_kw: { base: 0.3, amp: 0.3, noise: 0.1, phase: 3.2 },
    },
    episode: null,
    lastActiveMin: -35, // stopped reporting 35 min ago
  },
  {
    id: 'mach_laser',
    name: 'Laser Cutter LC-1',
    type: 'CUTTING',
    status: 'RUNNING',
    image: 'images/camera_lens.jpg',
    plantId: 'plant_secondary',
    externalDeviceId: 'dev-lsr-015',
    thresholds: { temperature_c: { max: 58 }, power_kw: { max: 10 } },
    telemetry: {
      temperature_c: { base: 42, amp: 4, noise: 0.7, phase: 5.9 },
      power_kw: { base: 5.8, amp: 1.6, noise: 0.35, phase: 0.1 },
      load_pct: { base: 60, amp: 14, noise: 2.5, phase: 0.1 },
    },
    episode: null,
  },
  {
    id: 'mach_testbench',
    name: 'Test Bench TB-1',
    type: 'TESTING',
    status: 'IDLE',
    image: 'images/force_sensor.jpg',
    plantId: 'plant_main',
    externalDeviceId: 'dev-tb-016',
    thresholds: { temperature_c: { max: 50 }, power_kw: { max: 4 } },
    telemetry: {
      temperature_c: { base: 29, amp: 1, noise: 0.3, phase: 4.8 },
      power_kw: { base: 0.4, amp: 0.2, noise: 0.1, phase: 4.8 },
    },
    episode: null,
    sensorFailure: true, // emits quality 'bad' readings in the last window
  },
];

module.exports = { MACHINES };
